[package]
name = "fluid-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
rayon = "1.10"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[[bin]]
name = "fluid-sim"
path = "src/main.rs"

